### ISSUE TITLE
Related property values not loaded for derived related classes

### ISSUE THREAD

**Issue by grigasp** [iTwin/imodel-native#229]
Schema:
```
Classes: 
- A
  - Properties: PropA
- B
  - Properties: PropB
- C
  - Derives from B
  - Properties: PropC

Relationships: 
- AB between A -> B
```

Data:
```
Instances:
- a of class A, PropA = "aaa"
- b of class B, PropB = "bbb"
- c of class C, PropB = "ccc", PropC = "ccc"
- ab of relationship AB, between instances a and b
- ac of relationship AB, between instances a and c
```

Rules:
```
{
  "id": "rules",
  "rules": [{
    "ruleType": "Content",
    "specifications": [{
      "specType": "ContentInstancesOfSpecificClasses",
      "classes": { "schemaName": "MySchema", "classNames": ["A"] },
      "relatedProperties": [{
        "propertiesSource": {
          "relationship": { "schemaName": "MySchema", "className": "AB" },
          "direction": "Forward"
        },
        "handleTargetClassPolymorphically": true
      }]
    }]
  }]
}
```

Expected result:
```
PropA: "aaa"
B:
  PropB: "bbb"
C:
  PropB: "ccc"
  PropC: "ccc"
```

Actual result:
```
PropA: "aaa"
B:
  PropB: "bbb"
C:
  PropB: "ccc"
  PropC: null
```
