### ISSUE TITLE
Presentation: Deadlock when using diagnostics

### ISSUE THREAD

**Issue by grigasp** [iTwin/imodel-native#263]
Reproduced when running load tests with the following config:
- backend:
  ```cmd
  set PROCESS_COUNT=16
  set SHARE_CACHES=1
  ```
- tests:
  ```yaml
  config:
    target: "http://localhost:3001/presentation-test-app/v1.0/mode/1/context/00000000-0000-0000-0000-000000000000/imodel/00000000-0000-0000-0000-000000000000/changeset/0"

    http:
      maxSockets: 1000
      timeout: 120
      extendedMetrics: false

    phases:
      # 100 users start the scenario one after another in 1 second intervals
      - name: "100 users"
        duration: 100
        arrivalRate: 1

    payload:
      path: "./datasets.csv"
      fields:
        - "iModelPath"
      order: sequence
      loadAll: true

    variables:
      operationGetNodes:
        - "PresentationRpcInterface-4.0.0-getPagedNodes"

    processor: "../lib/index.js"

  scenarios:
    - name: Full Models Tree
      beforeScenario: "createClientId"
      flow:
        - loop:
            - post:
                ifTrue: "iModelPath"
                url: "/{{ operationGetNodes }}"
                beforeRequest: "createModelsTreeRequestParams"
                afterResponse: "extractNodeKeysFromNodesResponse"
            - think: 0.1
          whileTrue: "hasParentNodeKeys"
  ```
- dataset: `BayTownProcessPlant.bim`

Looks like we're still adding items to diagnostics scope when it already being serialized to JSON.

![Image](https://user-images.githubusercontent.com/35135765/234546657-b6f7d851-1382-423f-81b8-67fb62902f56.png)
